const stockOptions = [
  { label: 'Reliance Industries (RELIANCE.NS)', value: 'RELIANCE.NS' },
  { label: 'Tata Consultancy Services (TCS.NS)', value: 'TCS.NS' },
  { label: 'Infosys Ltd (INFY.NS)', value: 'INFY.NS' },
  { label: 'HDFC Bank (HDFCBANK.NS)', value: 'HDFCBANK.NS' },
  { label: 'ICICI Bank (ICICIBANK.NS)', value: 'ICICIBANK.NS' },
  { label: 'State Bank of India (SBIN.NS)', value: 'SBIN.NS' },
  { label: 'Bharti Airtel Ltd (BHARTIARTL.NS)', value: 'BHARTIARTL.NS' },
  { label: 'Larsen & Toubro Ltd (LT.NS)', value: 'LT.NS' },
  { label: 'Hindustan Unilever (HINDUNILVR.NS)', value: 'HINDUNILVR.NS' },
  { label: 'Axis Bank (AXISBANK.NS)', value: 'AXISBANK.NS' },
  { label: 'Kotak Mahindra Bank (KOTAKBANK.NS)', value: 'KOTAKBANK.NS' },
  { label: 'Adani Enterprises (ADANIENT.NS)', value: 'ADANIENT.NS' },
  { label: 'Adani Ports (ADANIPORTS.NS)', value: 'ADANIPORTS.NS' },
  { label: 'Tata Steel (TATASTEEL.NS)', value: 'TATASTEEL.NS' },
  { label: 'Coal India (COALINDIA.NS)', value: 'COALINDIA.NS' },
  { label: 'ITC Ltd (ITC.NS)', value: 'ITC.NS' },
  { label: 'Bajaj Finance (BAJFINANCE.NS)', value: 'BAJFINANCE.NS' },
  { label: 'Bajaj Finserv (BAJAJFINSV.NS)', value: 'BAJAJFINSV.NS' },
  { label: 'Maruti Suzuki (MARUTI.NS)', value: 'MARUTI.NS' },
  { label: 'Mahindra & Mahindra (M&M.NS)', value: 'M&M.NS' },
  { label: 'NTPC Ltd (NTPC.NS)', value: 'NTPC.NS' },
  { label: 'UltraTech Cement (ULTRACEMCO.NS)', value: 'ULTRACEMCO.NS' },
  { label: 'Power Grid Corp (POWERGRID.NS)', value: 'POWERGRID.NS' },
  { label: 'Sun Pharma (SUNPHARMA.NS)', value: 'SUNPHARMA.NS' },
  { label: 'Dr. Reddy’s Laboratories (DRREDDY.NS)', value: 'DRREDDY.NS' },
  { label: 'Tech Mahindra (TECHM.NS)', value: 'TECHM.NS' },
  { label: 'HCL Technologies (HCLTECH.NS)', value: 'HCLTECH.NS' },
  { label: 'Wipro Ltd (WIPRO.NS)', value: 'WIPRO.NS' },
  { label: 'Nestle India (NESTLEIND.NS)', value: 'NESTLEIND.NS' },
  { label: 'Britannia Industries (BRITANNIA.NS)', value: 'BRITANNIA.NS' },
  { label: 'JSW Steel (JSWSTEEL.NS)', value: 'JSWSTEEL.NS' },
  { label: 'Cipla Ltd (CIPLA.NS)', value: 'CIPLA.NS' },
  { label: 'Grasim Industries (GRASIM.NS)', value: 'GRASIM.NS' },
  { label: 'Divi’s Laboratories (DIVISLAB.NS)', value: 'DIVISLAB.NS' },
  { label: 'HDFC Life (HDFCLIFE.NS)', value: 'HDFCLIFE.NS' },
  { label: 'SBI Life Insurance (SBILIFE.NS)', value: 'SBILIFE.NS' },
  { label: 'Tata Consumer (TATACONSUM.NS)', value: 'TATACONSUM.NS' },
  { label: 'Eicher Motors (EICHERMOT.NS)', value: 'EICHERMOT.NS' },
  { label: 'Asian Paints (ASIANPAINT.NS)', value: 'ASIANPAINT.NS' },
  { label: 'Havells India (HAVELLS.NS)', value: 'HAVELLS.NS' }
];

export default stockOptions;
